### ISSUE TITLE
The Y scale in the cpu plugin is too high

### ISSUE THREAD

**Issue by Magneticdud** [scanterog/munin-plugin-docker#4]
hi, running this plugin on a server with 16 cores, i see avg usage of each container around 3%, but because the scale of the Y is set to 24000%, it's invisible. There's any way i can lower the scale?

Thanks

**Comment by Magneticdud** [comment]
my workaround is to comment out line 92.

Actually, because my containers use very little cpu time, i changed it to a value 500 times smaller

`$graphlimit = $graphlimit / 5;`

Thanks for this plugin, very useful for monitoring

**Comment by letompouce** [comment]
Mine was to remove the `--upper-limit` arg:

    print "graph_args --base 1000 -r --lower-limit 0\n";
